spring.application.name=inventory-backend

spring.datasource.url=jdbc:postgresql://localhost:5444/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Change the lines 3, 4 and 5 with this if you are using PostgreSQL locally on your machine without docker
# Be sure to change the values in the placeholders <PLACEHOLDER> with your actual values from the local PostgreSQL
# spring.datasource.url=jdbc:postgresql://<EXTERNAL_HOST>:<PORT>/<DATABASE_NAME>
# spring.datasource.username=<YOUR_USERNAME>
# spring.datasource.password=<YOUR_PASSWORD>
